In [2]:
import numpy as np

In [3]:
np.zeros


<function numpy.zeros(shape, dtype=None, order='C', *, device=None, like=None)>

In [5]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
a = np.zeros((3,5))

In [7]:
a.shape

(3, 5)

In [9]:
a.ndim

2

In [10]:
a.size

15

In [12]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [14]:
type(np.array((2,3,4)))

numpy.ndarray

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full((2,3),np.pi)

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

In [19]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.arange(2,7)

array([2, 3, 4, 5, 6])

In [21]:
print(np.linspace(0, 5/3, 6))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [ ]:
def my_function(x,y,z):
    return

In [23]:
d = np.arange(3,5 , dtype= np.complex64)
print (d)

[3.+0.j 4.+0.j]
